# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\x02\x61i\"\x1d\n\tAIRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1c\n\nAIResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2;\n\tAIService\x12.\n\rGetAIResponse\x12\r.ai.AIRequest\x1a\x0e.ai.AIResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIREQUEST']._serialized_start=24
  _globals['_AIREQUEST']._serialized_end=53
  _globals['_AIRESPONSE']._serialized_start=55
  _globals['_AIRESPONSE']._serialized_end=83
  _globals['_AISERVICE']._serialized_start=85
  _globals['_AISERVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
