# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_pb2 as api__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Chat service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAIResponse = channel.unary_unary(
                '/api.AIService/GetAIResponse',
                request_serializer=api__pb2.AIRequest.SerializeToString,
                response_deserializer=api__pb2.AIResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Chat service
    """

    def GetAIResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAIResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAIResponse,
                    request_deserializer=api__pb2.AIRequest.FromString,
                    response_serializer=api__pb2.AIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Chat service
    """

    @staticmethod
    def GetAIResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.AIService/GetAIResponse',
            api__pb2.AIRequest.SerializeToString,
            api__pb2.AIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileProcessingServiceStub(object):
    """File processing service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFile = channel.unary_unary(
                '/api.FileProcessingService/ProcessFile',
                request_serializer=api__pb2.FileRequest.SerializeToString,
                response_deserializer=api__pb2.FileResponse.FromString,
                _registered_method=True)


class FileProcessingServiceServicer(object):
    """File processing service
    """

    def ProcessFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFile,
                    request_deserializer=api__pb2.FileRequest.FromString,
                    response_serializer=api__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.FileProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.FileProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileProcessingService(object):
    """File processing service
    """

    @staticmethod
    def ProcessFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.FileProcessingService/ProcessFile',
            api__pb2.FileRequest.SerializeToString,
            api__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
