# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x06health\")\n\x0b\x46ileRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\t\"L\n\x0c\x46ileResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x05tests\x18\x03 \x03(\x0b\x32\x0c.health.Test\"\x7f\n\x04Test\x12\x12\n\ncategories\x18\x01 \x01(\t\x12\x30\n\nparameters\x18\x02 \x03(\x0b\x32\x1c.health.Test.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32S\n\x15\x46ileProcessingService\x12:\n\x0bProcessFile\x12\x13.health.FileRequest\x1a\x14.health.FileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_TEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_FILEREQUEST']._serialized_start=24
  _globals['_FILEREQUEST']._serialized_end=65
  _globals['_FILERESPONSE']._serialized_start=67
  _globals['_FILERESPONSE']._serialized_end=143
  _globals['_TEST']._serialized_start=145
  _globals['_TEST']._serialized_end=272
  _globals['_TEST_PARAMETERSENTRY']._serialized_start=223
  _globals['_TEST_PARAMETERSENTRY']._serialized_end=272
  _globals['_FILEPROCESSINGSERVICE']._serialized_start=274
  _globals['_FILEPROCESSINGSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
